---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List ansible packages and register result to print with debug later
    yum:
      list: installed
    register: result
      
  - name: write lines to file
    copy:
      content: "{{ result }}"
      dest: "InstalledSoftwares.txt"
      
  - name: line insert
    lineinfile:
      path: "InstalledSoftwares.txt"
      line: "{{ ansible_ssh_host }}"
      insertbefore: BOF

  - debug:
        msg: "List of all programs on host has been created."
