---
- name: List all Softwares
  hosts: all

  tasks:
  - name: Initialize empty lists to store software names, host ip, and versions
    set_fact:
      snames: [ 'Names' ]
      sversions: [ 'Version' ]
      shost: [ 'Host IP' ]

  - name: List all software into the software variable in dictionary form
    yum:
      list: installed
    register: software

  - name: add name, host ip and version to lists 
    with_items: "{{ software | json_query('results[*]') }}"
    set_fact:
      snames: "{{ snames + [ item.name ] }}"
      shost: "{{ shost + [ ansible_ssh_host ] }}"
      sversions: "{{ sversions + [ item.version ] }}"

  - name: Register remote linux host with variable
    add_host:
        name: "192.168.1.41"
        VAR_NEW: "{{ snames | zip(sversions) | map('join', ', ') | zip(shost) | map('join', ', ') | join('\n') }}"

- name: List all Softwares
  hosts: 192.168.1.41
  tasks:
  - name: combine name and version list and write into csv file on control node delegrate_to
    copy:
      content: "{{ hostvars['192.168.1.41']['VAR_NEW'] }}"
      dest: "SoftwareList.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
