---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List ansible packages and register result to print with debug later
    yum:
      list: installed
    register: result
      
  - name: write lines to file
    copy:
      content: "{{ ansible_ssh_host }} + {{ result }}"
      dest: "InstalledSoftwares.xlsx"

  - debug:
        msg: "List of all programs on host has been created."
