---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List all software into the result variable
    command: yum list installed > "SoftwareListOn_{{ ansible_ssh_host }}.txt"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
