---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List ansible packages and register result to print with debug later
    yum:
      list: installed
    register: result
      
  - name: write lines to file
    copy:
      content: "{{ result }}"
      dest: "AllPrograms_{{ ansible_ssh_host }}.xlsx"
      
  - name: write lines to text file
    copy:
      content: "{{ result }}"
      dest: "file"

  - debug:
        msg: "List of all programs on host has been created."
