---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List all software into the result variable
    yum:
      list: installed
    register: software

  - name: line insert
    with_items: "{{ software | json_query('results[*].name') }}"
    vars:
      printvari: "{{ item }}"
    copy:
      content: "{{ printvari }}"
      dest: "SoftwareListOn_{{ ansible_ssh_host }}.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
