---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List all software into the software variable in dictionary form
    yum:
      list: installed
    register: software
    
  - name: Initialize empty lists to store software names and versions
    set_fact:
      snames: [ 'Names' ]
      sversions: [ 'Version' ]
      shost: [ 'Host IP' ]

  - name: add software names and versions to above mentioned lists
    with_items: "{{ software | json_query('results[*]') }}"
    set_fact:
      snames: "{{ snames + [ item.name ] }}"
      shost: "{{ shost + [ ansible_ssh_host ] }}"
      sversions: "{{ sversions + [ item.version ] }}"
    
  - name: combine name and version list and write into csv file
    copy:
      content: "{{ snames | zip(sversions) | map('join', ', ') | zip(shost) | map('join', ', ') | join('\n') }}"
      dest: "SoftwareList.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
