---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List all software into the result variable
    yum:
      list: installed
    register: software
    
  - name: line insert
    lineinfile:
      path: Input.txt
      line: "{{ item.results.name }} {{ item.results.version}}"
      insertbefore: EOF
    with_items:
    - "{{ software }}"

  - name: writes aboe list to file
    copy:
      content: "{{ software }}"
      dest: "SoftwareListOn_{{ ansible_ssh_host }}.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
