---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List ansible packages and register result to print with debug later
    yum:
      list: installed
      register: result

  - name: add list of all programs installed
    command: {{ result.stdout_lines }} > InstalledSoftwares.xlsx

  - debug:
        msg: "List of all programs on host has been created."
