---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102
  vars:
    listofsoftware: ""

  tasks:
  - name: List all software into the result variable
    yum:
      list: installed
    register: software
    
  - name: append contents into a variable
    listofsoftware: "{{ listofsoftware }}{{ item }}"
    with_items: "{{ software | json_query('results[*].name') }}"
    
  - name: line insert
    lineinfile:
      path: Input.txt
      line: "{{ listofsoftware }}"
      insertbefore: BOF


  - name: writes aboe list to file
    copy:
      content: "{{ software }}"
      dest: "SoftwareListOn_{{ ansible_ssh_host }}.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
