---
- name: Encrypt/Decrypt String
  hosts: 192.168.56.102

  tasks:
  - name: List all software into the result variable
    yum:
      list: installed
    register: result

  - name: var=item
    with_items: "{{ result | json_query('results[*].name') }}"

  - name: writes aboe list to file
    copy:
      content: "{{ json_query }}"
      dest: "SoftwareListOn_{{ ansible_ssh_host }}.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
